<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>MG.Dynamic</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Debug.ps1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Debug.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
	
  <ItemGroup>
	  <Using Include="System.Management.Automation" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management.Automation" Version="7.6.0-preview.5" />
  </ItemGroup>

</Project>
